---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: test-010-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: test-010-2
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: test-010-1
- kind: ServiceAccount
  name: ambassador
  namespace: test-010-2
  